version: '3.8'

services:
  moge-api:
    build: .
    container_name: moge-api-container
    image: moge-api:latest
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
      - ./output:/app/output
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped